sln_ajinomoto/Models/Tareas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetoTecnicoAjinomoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionEstado { get; set; }
        public Nullable<int> IdEstadoTarea { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
    }
}

sln_ajinomoto/Controllers/TareasController.cs
using RetoTecnicoAjinomoto.Models;
using RetoTecnicoAjinomoto.Service.Implementation;
using RetoTecnicoAjinomoto.Service.Interface;
using RetoTecnicoAjinomoto.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Web.Http;
using System.Web.Mvc;

namespace RetoTecnicoAjinomoto.Controllers
{
    //[Authorize]
    public class TareasController : Controller
    {
        // GET: Tareas
        public ActionResult Index()
        {
            using (TareasDbModels context = new TareasDbModels())
            {
                var listadoTareas = context.Tareas.ToList();
                foreach (var item in listadoTareas)
                {
                    //iteración de la descripción del estado por cada tarea.
                    item.DescripcionEstado = context.EstadoTarea.Where(x => x.Id == item.IdEstadoTarea).FirstOrDefault().Nombre;
                }
                ViewBag.ItemsTarea = listadoTareas;
                return View("~/Views/Tareas/Index.cshtml", listadoTareas);
            }
        }

        [HttpGet]
        public JsonResult ObtenerTareas()
        {
            ITareaService _tareaService = new TareaService();
            // Devuelve el array como un JSON
            return Json(_tareaService.ObtenerEstadoTareas(), JsonRequestBehavior.AllowGet);
        }


        // GET: Tareas/Details/5
        public ActionResult Details(int id)
        {
            using (TareasDbModels context = new TareasDbModels())
            {
                return View(context.Tareas.Where(x => x.Id == id)); //recupera el contexto para ser seteado en la vista detalle
            }
        }


        // GET: Tareas/Create
        public ActionResult Create()
        {

            using (TareasDbModels context = new TareasDbModels())
            {
                var estadosTarea = context.EstadoTarea.ToList();

                var modelo = new TareasViewModelRegister
                {
                    ListaEstadoTareas = estadosTarea
                };

                return View("~/Views/Tareas/Create.cshtml", modelo);
            }

        }

        // POST: Tareas/Create
        [HttpPost]
        public ActionResult Create(Tareas oTareas)
        {
            ITareaService _tareaService = new TareaService();
            return Json(_tareaService.RegistrarTarea(oTareas));

        }

        // GET: Tareas/Edit/5
        public ActionResult Edit(int? id)
        {
            using (TareasDbModels context = new TareasDbModels())
            {
                var estadosTarea = context.EstadoTarea.ToList();
                var modelo = new TareasViewModelRegister
                {
                    Tarea = context.Tareas.Where(x => x.Id == id).FirstOrDefault(),
                    ListaEstadoTareas = estadosTarea
                };

                return View("~/Views/Tareas/Edit.cshtml", modelo);

                //return View();
            }
        }

        // POST: Tareas/Edit/5
        [HttpPost]
        public ActionResult Edit(Tareas oTareas)
        {
            ITareaService _tareaService = new TareaService();
            return Json(_tareaService.EditarTarea(oTareas));

        }

        // GET: Tareas/Delete/5
        public ActionResult Delete(int id)
        {
            using (TareasDbModels context = new TareasDbModels())
            {
                return View(context.Tareas.Where(x => x.Id == id).FirstOrDefault());
            }
        }

        // POST: Tareas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (TareasDbModels context = new TareasDbModels())
                {
                    Tareas oTareas = context.Tareas.Where(x => x.Id == id).FirstOrDefault();
                    context.Tareas.Remove(oTareas); //remueve la tarea de la tabla haciendo referencia al contexto modelo.
                    context.SaveChanges();
                    var listadoTareas = context.Tareas.ToList();
                    foreach (var item in listadoTareas)
                    {
                        item.DescripcionEstado = context.EstadoTarea.Where(x => x.Id == item.IdEstadoTarea).FirstOrDefault().Nombre;
                    }
                    ViewBag.ItemsTarea = listadoTareas;
                }

                return View("~/Views/Tareas/Index.cshtml");
            }
            catch
            {
                return View();
            }
        }
    }
}

sln_ajinomoto/Views/Tareas/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<head>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li><h2 style="color:white">Crear Tarea</h2></li>
                </ul>
                
            </div>
            <div class="navbar-collapse right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Regresar", "Index", "Tareas", new {  })</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br />
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <label>Título</label>
            </div>
            <div class="col-md-10">
                <input type="text" id="titulo" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Descripción</label>
            </div>
            
            <div class="col-md-10">
                <input type="text" id="descripcion" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Estado</label>
            </div>
            <div class="col-md-10">
                <select id="miSelect"></select>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <input type="button" value="Registrar" class="btn btn-default" onclick="guardarTarea()" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">


    $(document).ready(function () {
        debugger;
        $.ajax({
            url: 'ObtenerTareas',  // Acción del controlador
            type: 'GET',
            dataType: 'json', // Tipo de datos que se espera recibir
            success: function (data) {
                // Obtén el elemento <select>
                const select = document.getElementById("miSelect");

                // Limpiar el <select> antes de llenarlo
                select.innerHTML = '';

                // Iterar sobre el array y crear elementos <option>
                data.forEach((opcion) => {
                    const option = document.createElement("option");
                    option.value = opcion.Id; // Puedes establecer un valor diferente si lo deseas
                    option.textContent = opcion.Nombre; // Establecer el texto que se mostrará
                    select.appendChild(option); // Agregar el <option> al <select>
                });
            },
            error: function (xhr, status, error) {
                console.error("Error al obtener las tareas:", error); // Manejo de errores
            }
        });
    });


    function guardarTarea() {
        debugger;
        // Crear un objeto JSON
        const select = document.getElementById("miSelect");
        tareaJson = {
            titulo: $("#titulo").val(),
            descripcion: $("#descripcion").val(),
            idEstadoTarea: select.value
        };

        // Llamada AJAX usando POST para enviar el objeto JSON
        $.ajax({
            url: 'Create',  // Acción del controlador
            type: 'POST',
            contentType: 'application/json',  // Especifica que estás enviando JSON
            data: JSON.stringify(tareaJson),  // Convierte el objeto a formato JSON
            success: function (response) {
                debugger;

                

                Swal.fire({
                    title: (response.Codigo == "OK") ? '¡Éxito!' : "Error",
                    text: response.Mensaje,
                    icon: 'success',
                    timer: 20000,
                    confirmButtonText: (response.Codigo == "OK") ? 'OK' : "ERROR"
                });

                if (response.Codigo == "OK") {
                    setTimeout(function () {
                        window.location.href = 'Index';
                    }, 5000); // Redirige después de 3 segundos
                   
                }
                
                
            },
            error: function (xhr, status, error) {
                debugger;
                alert("Error: " + error);
            }
        });
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sln_ajinomoto/Views/Tareas/Delete.cshtml
@model RetoTecnicoAjinomoto.Models.Tareas

@{
    ViewBag.Title = "Eliminar Tarea";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li><h2 style="color:white">Eliminar Tarea</h2></li>
                </ul>

            </div>
            <div class="navbar-collapse right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Regresar", "Index", "Tareas")</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<br />
<h3>¿Está seguro de eliminar la tarea?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" />
        </div>
    }
</div>

sln_ajinomoto/Views/Tareas/Details.cshtml
@model RetoTecnicoAjinomoto.Models.Tareas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tareas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdEstadoTarea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEstadoTarea)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
</p>

sln_ajinomoto/Views/Tareas/Edit.cshtml
@model RetoTecnicoAjinomoto.ViewModels.TareasViewModelRegister

@{
    ViewBag.Title = "Edit";
}
<head>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li><h2 style="color:white">Editar Tarea</h2></li>
                </ul>

            </div>
            <div class="navbar-collapse right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Regresar", "Index", "Tareas")</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<br />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@

        <div class="form-group">
            @Html.LabelFor(model => model.Tarea.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarea.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarea.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarea.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarea.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarea.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarea.IdEstadoTarea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Tarea.IdEstadoTarea,
                new SelectList(Model?.ListaEstadoTareas, "Id", "Nombre"), "Seleccione un estado", new { @class = "form-control", id = "estadoDropdown" })
            </div>

            @*@Html.LabelFor(model => model.IdEstadoTarea, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdEstadoTarea, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdEstadoTarea, "", new { @class = "text-danger" })
                </div>*@
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" onclick="guardarTarea()"/>
            </div>
        </div>
    </div>
}

<script type="text/javascript">


    function guardarTarea() {
        debugger;
        var url = window.location.href;

        // Extraer el ID de la URL
        var id = url.substring(url.lastIndexOf('/') + 1);

        // Crear un objeto JSON
        tareaJson = {
            id: id,
            titulo: $('input[name="Tarea.Titulo"]').val(),
            descripcion: $('input[name="Tarea.Descripcion"]').val(),
            idEstadoTarea: $('#estadoDropdown').val()
        };

        // Llamada AJAX usando POST para enviar el objeto JSON
        $.ajax({
            url: 'Edit',  // Acción del controlador
            type: 'POST',
            contentType: 'application/json',  // Especifica que estás enviando JSON
            data: JSON.stringify(tareaJson),  // Convierte el objeto a formato JSON
            success: function (response) {
                debugger;



                Swal.fire({
                    title: (response.Codigo == "OK") ? '¡Éxito!' : "Error",
                    text: response.Mensaje,
                    icon: 'success',
                    timer: 20000,
                    confirmButtonText: (response.Codigo == "OK") ? 'OK' : "ERROR"
                });

                if (response.Codigo == "OK") {
                    setTimeout(function () {
                        window.location.href = 'Index';
                    }, 5000); // Redirige después de 3 segundos

                }


            },
            error: function (xhr, status, error) {
                debugger;
                alert("Error: " + error);
            }
        });
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sln_ajinomoto/Views/Tareas/Index.cshtml
@{
    ViewBag.Title = "Tareas";
}



<h2>Listado de Tareas</h2>
@*<h4>Filtro por Estado</h4>
<div class="form-group">
    Estado  @Html.DropDownListFor(model => model.Tarea.IdEstadoTarea,
new SelectList(Model?.ListaEstadoTareas, "Id", "Nombre"), "Seleccione una categoría")
    @Html.ActionLink("Buscar", "Search", "Tareas", new { id = Model.Tarea?.IdEstadoTarea }, new { @class = "btn btn-info" })
</div>*@


<html>
<head>

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                    <div class="navbar-header">
                        @Html.ActionLink("AJINOMOTO (To-Do-List)", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse right">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Cerrar Sesion", "Index", "Tareas")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
            <p>
                @Html.ActionLink("Crear", "Create", "Tareas", "", new { @class = "btn btn-success" })
            </p>
            <table class="table">
                <tr>
                    <th>
                        Titulo
                    </th>
                    <th>
                        Descripción
                    </th>
                    <th>
                        Estado
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in ViewBag.ItemsTarea)
                {
                    <tr>
                        <td>
                            @item.Titulo
                        </td>
                        <td>
                            @item.Descripcion
                        </td>
                        <td>
                            @item.DescripcionEstado
                        </td>

                        <td>
                            @Html.ActionLink("Editar", "Edit", "Tareas", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                            @Html.ActionLink("Eliminar", "Delete", "Tareas", new { id = item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }

            </table>
        </body>
        </html>